// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWpoHbpRXr6EIxzc0rS3rT6rSwaIzVDbw',
    appId: '1:469688883395:android:84aa4613e3308e851faa76',
    messagingSenderId: '469688883395',
    projectId: 'app-cipher-e31cc',
    storageBucket: 'app-cipher-e31cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWYO24SMdHuxjUEkeHeH912fFKdkJKSG0',
    appId: '1:469688883395:ios:cb30c45cf48d53651faa76',
    messagingSenderId: '469688883395',
    projectId: 'app-cipher-e31cc',
    storageBucket: 'app-cipher-e31cc.appspot.com',
    androidClientId: '469688883395-u0jtagoe6o2io2gshcncci9uk93j9ncm.apps.googleusercontent.com',
    iosClientId: '469688883395-op772o1th655b4642n9vcdha4ieib22i.apps.googleusercontent.com',
    iosBundleId: 'br.com.renan.theCipherApp',
  );
}
