name: CI

on:
  push:
    branches:
      - develop
      - main

env:
  FLUTTER_VERSION: 3.0.4
  java_version: "12.x"
  PUB_CACHE: ~/.pub-cache

jobs:
  deploy_app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [macos-latest]
         include:
          - os: macos-latest
            flutter_path: /Users/runner/hostedtoolcache/flutter
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - name: Flutter Setup
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ${{ runner.tool_cache }}/flutter
          key: ${{ env.FLUTTER_VERSION }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
      - uses: dorny/test-reporter@v1.4.2
        with:
          name: test-results
          path: test-results.json
          reporter: flutter-json
      - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          min_coverage: 0

      - run: flutter build apk
      
      - run: flutter build ipa

      - name: Upload android build artifacts
        uses: actions/upload-artifact@v2
        with:
           name: cipher_abb_android
           path: ${{ github.workspace }}/build/app/outputs/bundle/release

      # - name: Upload ios build artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #      name: cipher_abb_ios
      #      path: ${{ github.workspace }}/build/app/outputs/bundle/release
