name: CI_CD

on:

  workflow_dispatch:
    inputs:
      beta:
        description: 'Release Beta App Play Store'
        required: true
        default: 'beta' 
        
env:
  FLUTTER_VERSION: 3.0.4
  PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
  java_version: "12.x"

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - run: flutter --version
      - run: flutter pub get
      # - run: flutter test --coverage
      # - run: flutter test --machine > test-results.json
      # - uses: dorny/test-reporter@v1.4.2
      #   with:
      #     name: test-results
      #     path: test-results.json
      #     reporter: flutter-json
      # - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
      #   with:
      #     min_coverage: 0

      - name: Define version code with offset
        env:
           RUN_NUMBER: ${{ github.run_number }}
           INITIAL_VERSION_CODE: 73
        run: |
              VERSION_CODE=$((INITIAL_VERSION_CODE + RUN_NUMBER))
               echo "version_code=$VERSION_CODE" >> $GITHUB_ENV


      - name: Update version code
        uses: chkfung/android-version-actions@v1.1
        with:
           gradlePath: android/app/build.gradle
           versionCode: ${{ env.version_code }}
           versionName: 1.0.0

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.java_version }} 

           
       # Setup Ruby, Bundler, and Gemfile dependencies
      - uses: ruby/setup-ruby@8029ebd6e5bd8f4e0d6f7623ea76a01ec5b1010d
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android


      - name: Configure Keystore
        run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
        env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        working-directory: android


      - name: Fastlane exec
        run: bundle exec fastlane beta
        env: 
            PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android


      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
           name: assets
           path: |
              ${{ github.workspace }}/app/build/outputs/bundle/release
